//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNAtours.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Carts = new HashSet<Cart>();
            this.Order_Line = new HashSet<Order_Line>();
            this.Product_Category_Mapping = new HashSet<Product_Category_Mapping>();
        }
    
        public int Id { get; set; }
        public Nullable<int> VisaId { get; set; }
        public Nullable<decimal> VisaPrice { get; set; }
        public Nullable<int> InsuranceId { get; set; }
        public Nullable<decimal> InsurancePrice { get; set; }
        public string RouteName { get; set; }
        public string DepartureCities { get; set; }
        public Nullable<bool> IsSurChargeCity { get; set; }
        public Nullable<decimal> SurChargeCiteFee { get; set; }
        public string DepartureDates { get; set; }
        public Nullable<bool> IshightSeasons { get; set; }
        public Nullable<decimal> SurChargeDateFee { get; set; }
        public Nullable<bool> IsIncludedTourTipping { get; set; }
        public Nullable<decimal> TourTipping { get; set; }
        public Nullable<int> TourDays { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<int> Booked_Qty { get; set; }
        public Nullable<bool> FullStatus { get; set; }
        public string Description { get; set; }
        public string IncludedCities { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
        public string Image4 { get; set; }
        public string Image5 { get; set; }
        public string Image6 { get; set; }
        public string Image7 { get; set; }
        public string Image8 { get; set; }
        public string Image9 { get; set; }
        public string Image10 { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual Insurance Insurance { get; set; }
        public virtual ICollection<Order_Line> Order_Line { get; set; }
        public virtual ICollection<Product_Category_Mapping> Product_Category_Mapping { get; set; }
        public virtual Visa Visa { get; set; }
    }
}
