//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNAtours.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visa
    {
        public Visa()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> VisaTypeId { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual VisaType VisaType { get; set; }
    }
}
